id: bryo
title: Bryozoan Attribute Ontology
github_org: megbalk
repo: bryo
import_group:
  products:
    - id: ro
    - id: bfo
    - id: pato
    - id: oba
    - id: bspo
    - id: iao
    - id: bco
    - id: uberon
    - id: clyh
    - id: ncbitaxon
      mirror_from: http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl